// livros-servidor/clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';
import { LivroMongo } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css'],
})
export class LivroListaComponent implements OnInit {
  editoras: Array<Editora> = [];
  livros: LivroMongo[] = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().then((livros) => {
      this.livros = livros;
    });
  }

  excluir(codigo: string): void {
    this.servLivros.excluir(codigo).then(() => {
      this.servLivros.obterLivros().then((livros) => {
        this.livros = livros;
      });
    });
  }

  obterNome(codEditora: number): string {
    return this.servEditora.getNomeEditora(codEditora);
  }
}

<main class="container">
  <br />
  <table class="table table-striped">
    <thead class="table-dark text-white">
      <tr>
        <th>Título</th>
        <th>Resumo</th>
        <th>Autores</th>
        <th>Editora</th>
        <th>Opções</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>{{ livro.titulo }}</td>
        <td>{{ livro.resumo }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
        <td>{{ obterNome(livro.codEditora) }}</td>
        <td>
          <button
            class="btn btn-danger"
            (click)="excluir(livro.codigo.toString())"
          >
            Excluir
          </button>
        </td>
      </tr>
    </tbody>
  </table>
</main>

// livros-servidor/clientes/livros-react/src/LivroLista.js
import React, { useState, useEffect } from "react";
import ControleLivro from "./controle/ControleLivros";
import ControleEditora from "./controle/ControleEditora";
import './App.css';

const controleLivros = new ControleLivro("http://localhost:3030/livros");
const controleEditora = new ControleEditora();

const LinhaLivro = (props) => {
  const { livro, excluir, getNomeEditora } = props;
  const nomeEditora = getNomeEditora;

  return (
    <tr>
      <td>
        <p>{livro.titulo}</p>
        <button type="button" className="btn btn-danger" onClick={() => excluir(livro.codigo)}>Excluir</button>
      </td>
      <td>{livro.resumo}</td>
      <td>{nomeEditora(livro.codEditora)}</td>
      <td>
        <ul>
          {livro.autores.map((autor, index) => (
            <li key={index}>{autor}</li>
          ))}
        </ul>
      </td>
    </tr>
  );
}

const LivroLista = () => {
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    async function fetchLivros() {
      try {
        const livrosData = await controleLivros.obterLivros();
        setLivros(livrosData);
        setCarregado(true);
      } catch (error) {
        console.error(error);
      }
    }

    fetchLivros();
  }, []);

  const excluir = async (codigo) => {
    try {
      const excluido = await controleLivros.excluir(codigo);
      if (excluido) {
        const livrosAtualizados = livros.filter((livro) => livro.codigo !== codigo);
        setLivros(livrosAtualizados);
      }
    } catch (error) {
      console.error(error);
    }
  }

  return (
    <main className="container">
      <h1>Catálogo de Livros</h1>
      <table className="table table-hover">
        <thead className="table-dark">
          <tr>
            <th>Título</th>
            <th>Resumo</th>
            <th>Editora</th>
            <th>Autores</th>
          </tr>
        </thead>
        <tbody>
          {livros.map(livro => (
            <LinhaLivro
              key={livro.codigo}
              livro={livro}
              excluir={excluir}
              getNomeEditora={controleEditora.getNomeEditora}
            />
          ))}
        </tbody>
      </table>
    </main>
  )
}

export default LivroLista;
